[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/relatorio-forro-caju.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline; filename=\"Relatório de Op. - Forró Caju.pdf\""

[[headers]]
  for = "/relatorio-corrida-tiradentes.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline; filename=\"Relatório de Evento – CORRIDA TIRADENTES.pdf\""